services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/budgetapp
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      ENVIRONMENT: development
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: budgetapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./backend
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/budgetapp
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      CELERY_BROKER_URL: redis://redis:6379/0
      ENVIRONMENT: development

volumes:
  postgres_data:
