"""Add transfer category type and savings/transfer allocation tables

Revision ID: 73c49299cbbe
Revises: 
Create Date: 2025-06-17 12:17:59.716923

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c49299cbbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
